# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stuperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dockerabdulrhman.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_36e9801cc02948d5916568076d75f75b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b112324e46eb4a4ebeb3c210cd39fc26 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dockerabdulrhman.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_36e9801cc02948d5916568076d75f75b }}/stuperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stuperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_13569247cb3c4d7bb86b24c70b42ad49 }}
        images: 'dockerabdulrhman.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_36e9801cc02948d5916568076d75f75b }}/stuperformance:${{ github.sha }}'